site_name: mpmsub
site_description: Memory-aware multiprocessing subprocess execution library
site_author: Jon Palmer
site_url: https://nextgenusfs.github.io/mpmsub/

repo_name: nextgenusfs/mpmsub
repo_url: https://github.com/nextgenusfs/mpmsub
edit_uri: edit/main/docs/

theme:
  name: material
  palette:
    # Palette toggle for light mode
    - scheme: default
      primary: blue
      accent: blue
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    # Palette toggle for dark mode
    - scheme: slate
      primary: blue
      accent: blue
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - navigation.path
    - navigation.top
    - search.highlight
    - search.share
    - content.code.copy
    - content.code.annotate

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          options:
            docstring_style: google
            show_source: true
            show_root_heading: true
            show_root_toc_entry: false
            merge_init_into_class: true

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - admonition
  - pymdownx.details
  - attr_list
  - md_in_html
  - tables
  - footnotes
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

nav:
  - Home: index.md
  - User Guide:
    - Adding Jobs: guide/jobs.md
  - API Reference:
    - Overview: api/overview.md

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/nextgenusfs/mpmsub
    - icon: fontawesome/brands/python
      link: https://pypi.org/project/mpmsub/

copyright: Copyright &copy; 2025 Jon Palmer
