name: Create Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version number (e.g., 2025.01.15)'
        required: true
        type: string
      prerelease:
        description: 'Mark as pre-release'
        required: false
        type: boolean
        default: false

jobs:
  create-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write

    steps:
    - uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -e .[dev]

    - name: Update version in pyproject.toml
      run: |
        sed -i 's/version = ".*"/version = "${{ github.event.inputs.version }}"/' pyproject.toml

    - name: Run tests
      run: |
        pytest --cov=mpmsub
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        black --check .

    - name: Commit version update
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add pyproject.toml
        git commit -m "Bump version to ${{ github.event.inputs.version }}" || exit 0

    - name: Push changes
      run: git push

    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: v${{ github.event.inputs.version }}
        release_name: Release v${{ github.event.inputs.version }}
        body: |
          Release v${{ github.event.inputs.version }}
          
          ## Changes
          
          See the [changelog](CHANGELOG.md) for details.
          
          ## Installation
          
          ```bash
          pip install mpmsub==${{ github.event.inputs.version }}
          ```
        draft: false
        prerelease: ${{ github.event.inputs.prerelease }}
